print("Welcome to Gabriel's Mad Libs")
noun1 = raw_input("Give me a noun(objects plz):")
noun2 = raw_input("Give me a noun(objects plz):")
noun3 = raw_input("Give me a noun(a place plz):")
adjective1 = raw_input("Gimme a adjective:")
verb1 = raw_input("Gimme a verb:")

print("Gabe loves " + noun1 + " and " + noun2 + ".")
print("But wanting to combine those for the last time before " + noun3 + " closes.")
print("Although Gabe's craving was destined to be had his car had just broken down the day before. So due to his " + adjective1 + " Gabe called an uber and got abducted by the MIB.")
print("Gabe now " + verb1 + " aliens.")
